version: '3.3'

networks:
  mh_network:
    driver: bridge

volumes:
  mhv_node_modules:

services:
  mariadb:
    container_name: mhc_mariadb
    image: mariadb:10.9.4
    restart: always
    networks:
      - mh_network
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=medihome2022
      - MARIADB_DATABASE=${MARIADB_DATABASE:-mh_database}
      - MARIADB_USER=${MARIADB_USER:-medihome}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-mh123456}
    ports:
      - "7106:3306"

  nestjs:
    container_name: mhc_nestjs
    image: mhi_nestjs_${NODE_ENV:-development}:1.0.0
    restart: unless-stopped
    networks:
      - mh_network
    depends_on:
      - mariadb
    build:
      dockerfile: Dockerfile
      context: "./"
      target: ${NODE_ENV:-development}
    volumes:
      - ./:/app/
      - mhv_node_modules:/app/node_modules/
    command: ["sh", "-c", "npm run start:${NODE_ENV:-development}"]
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${NESTJS_PORT:-3000}:${NESTJS_PORT:-3000}"

