version: '3.3'

networks:
  mh_network:
    driver: bridge

services:
  mariadb:
    container_name: mhc_mariadb
    image: mariadb:10.9.4
    restart: always
    networks:
      - mh_network
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=medihome2022
      - MARIADB_DATABASE=${MARIADB_DATABASE:-mh_database}
      - MARIADB_USER=${MARIADB_USER:-medihome}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-mh123456}

  nestjs:
    container_name: mhc_nestjs
    image: mhi_nestjs_${NODE_ENV:-staging}:1.0.0
    restart: unless-stopped
    networks:
      - mh_network
    depends_on:
      - mariadb
    build:
      dockerfile: Dockerfile
      context: "./"
      target: ${NODE_ENV:-staging}
    command: ["sh", "-c", "npm run migration:run && npm run start:${NODE_ENV:-staging}"]
    environment:
      - NODE_ENV=${NODE_ENV:-staging}

  nginx:
    container_name: mhc_nginx
    image: nginx:1.23.2-alpine
    depends_on:
      - nestjs
      - mariadb
    restart: always
    networks:
      - mh_network
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
